name: form_task
description: "Form Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  easy_localization: ^3.0.8
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  logger_service:
    git:
      url: https://github.com/foresightmobile/logger_service.git
      ref: main
  meta: ^1.16.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  flutter_gen: ^5.12.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
        - asset: assets/fonts/CourierPrime-Italic.ttf
        - asset: assets/fonts/CourierPrime-BoldItalic.ttf
        - asset: assets/fonts/CourierPrime-Bold.ttf
scripts:
generator: dart pub run build_runner build --delete-conflicting-outputs